= LexFCS Data Views
:description: FCS DataViews for Lex Search.


Data formats for the representation of results.


== Lexical Data View

The _Lexical Data View_ (Lex Data View) is the mandatory serialisation of search results for _Lexical Search_ queries. It structures information into key and multiple values pairs. More details in <<LexFCS Data Model>>.

[%noheader,cols="1h,2"]
|===
|Description
|The representation of a lexical resource

|MIME type
|`application/x-clarin-fcs-lex+xml`

|Payload Disposition
|_inline_

|Payload Delivery
|_send-by-default_ (`REQUIRED`)

|Recommended Short Identifier
|`lex` (`RECOMMENDED`)

|XML Schema
|link:attachments/DataView-Lex.xsd[DataView-Lex.xsd]
|===

The Lexical Data View is serialised as XML in the `<fcs:DataView>` element, specified in the <<ref:CLARIN-FCSCore2,FCS Core 2 specification>> (section "Result Format", §2.2.3). The elements `<lex:Entry>`, `<lex:Field>` and `<lex:Value>` with their attributes are the direct serialisation of the <<LexFCS Data Model,Data Model>>.

A minimal example can be seen at <<dv-lex-basic>>. A few more targeted examples can be found in <<Serialisation with the Lexical Data View>> demonstrating edge cases and special features when using this Data View.

.Example of basic Lexical Data View
[source#dv-lex-basic,xml]
----
<!-- potential @pid and @ref attributes omitted -->
<fcs:DataView type="application/x-clarin-fcs-lex+xml" xmlns:fcs="http://clarin.eu/fcs/resource">
  <lex:Entry xmlns:lex="http://clarin.eu/fcs/dataview/lex">
    <lex:Field type="lemma">
      <lex:Value xml:lang="de">Becher</lex:Value>
    </lex:Field>
    <!-- … -->
  </lex:Entry>
</fcs:DataView>
----

Complete serialisation examples in the _Lexical Data View_ are provided along with this specification.


== Extension of the Hits Data View for LexFCS

The _Generic Hits (HITS)_ Data View is mandatory in <<ref:CLARIN-FCSCore2,FCS Core 2 specification>> (section "Basic Search", §2.2.3.2). This specification extends the `<hits:Hit>` element with an optional `@kind` attribute (see <<Using the @kind Attribute>>), which provides information on the content of the Hit result.

[%noheader,cols="1h,2"]
|===
|Description
|The representation of the hit

|MIME type
|`application/x-clarin-fcs-hits+xml`

|Payload Disposition
|_inline_

|Payload Delivery
|_send-by-default_ (`REQUIRED`)

|Recommended Short Identifier
|`hits` (`RECOMMENDED`)

|XML Schema
|link:attachments/DataView-LexHits.xsd[DataView-LexHits.xsd], based on https://github.com/clarin-eric/fcs-misc/blob/main/fcs-core-2/attachments/DataView-Hits.xsd["DataView-Hits.xsd"]
|===

.Example of basic *Hits* Data View
[source#dv-hits-basic,xml]
----
<!-- potential @pid and @ref attributes omitted -->
<fcs:DataView type="application/x-clarin-fcs-hits+xml" xmlns:fcs="http://clarin.eu/fcs/resource">
  <hits:Result xmlns:hits="http://clarin.eu/fcs/dataview/hits">The quick brown <hits:Hit>fox</hits:Hit> jumps over the lazy<hits:Hit>dog</hits:Hit>.</hits:Result>
</fcs:DataView>
----

=== Using the @kind Attribute

To extend the Hits Data View, the `<hits:Hit>` element is reused as per the <<ref:CLARIN-FCSCore2,FCS Core 2 Specification>>, but with the additional optional `@kind` attribute, which provides content hinting. The values of the `@kind` attribute follow the scheme `lex-<FIELD-TYPE>`, e.g. `lex-lemma` for lemma, `lex-pos` for part of speech (POS) tags etc.
Textual content outside of `<hits:Hit>` is displayed unchanged.

.Example of extended Hits Data View with additional `@kind` attributes
[source#dv-lexhits,xml]
----
<fcs:DataView type="application/x-textplus-fcs-hits+xml" xmlns:fcs="http://clarin.eu/fcs/resource">
  <hits:Result xmlns:hits="http://clarin.eu/fcs/dataview/hits"><hits:Hit kind="lex-lemma">Apple</hits:Hit>: <hits:Hit kind="lex-pos">NOUN</hits:Hit>. <hits:Hit kind="lex-definition">An apple is an edible fruit produced by an apple tree.</hits:Hit></hits:Result>
</fcs:DataView>
----

Endpoints `MUST` generate responses that are valid according to the XML schema link:attachments/DataView-LexHits.xsd["DataView-LexHits.xsd"].
