= Summary and Interface Specification
:description: SRU Explain and SearchRetrieve for FCS 2

== Summary of Changes

This specification extends the <<ref:CLARIN-FCSCore2,_CLARIN Federated Content Search (CLARIN-FCS) - Core 2_>> specification in the following ways:

* introducing a new query language, <<LexCQL,LexCQL>>, based on the <<ref:LOC-CQL,Contextual Query Language (CQL)>> to allow querying lexical resources,
* extending the basic <<Extension of the Hits Data View for LexFCS,Hits Data View>> for inline markup and adding a new <<Lexical Data View,Lexical Data View>>,
* extending the CLARIN-FCS _Endpoint Description_ with the _Lexical Search_ Capability.


== Discovery

The CLARIN-FCS SRU _explain_ response is extended by adding the _Lexical Search_ capability and _Lexical_ Data View to the _Endpoint Description_ to support client auto-configuration.


=== Capabilities

The _Lexical Search_ capability indicates to clients that the FCS endpoint supports searches through lexical resources using <<LexCQL,LexCQL>> and serializes results in the <<LexFCS Data Views,LexFCS Data Views>>.

.New Lexical Search Capability
[%header,cols="1e,3m,2"]
|===
|Name
|Capability Identifier
|Summary

|Lexical Search
|\http://clarin.eu/fcs/capability/lexical-search/1.0
|Structured search in lexical resources
|===

// TODO: explanation about versioning and how endpoints/clients should behave
// TODO: lex capability version equals LexFCS spec version
// TODO: capability without version should behave as legacy version of LexFCS spec

=== Endpoint Description

The _Endpoint Description_ is extended by a mandatory `<ed:SupportedLexFields>` element describing supported lexical fields for querying and results. The `<ed:SupportedDataView>` element supports the additional <<Lexical Data View,Lexical Data View>> which has its own MIME type and `@id` value.

The `<ed:EndpointDescription>` element is extended by

* one `<ed:SupportedLexFields>` element (`REQUIRED` if endpoint supports _Lexical Search_)
+
A list of field types that are generally supported by this endpoint. This list is composed of one or more `<ed:SupportedLexField>` elements. The content of a `<ed:SupportedLexField>` `MUST` be the identifier of a field type (see <<Field>>), e.g. `lemma`. Each `<ed:SupportedLexField>` element `MUST` carry an `@id` attribute. The value of the `@id` attribute is used in the `<ed:Resource>` element to indicate, which field types are supported by each resource (see below).
+
This list `MUST NOT` include duplicate entries regarding the content of the `<ed:SupportedLexField>` elements and their `@id` identifier.
+
The value of the `@id` attribute `MUST NOT` contain the characters `,` (comma) or `;` (semicolon).

The `<ed:Resource>` element is extended by

* one `<ed:AvailableLexFields>` element (`REQUIRED` if endpoint supports _Lexical Search_ capability)
+ 
The `<ed:AvailableLexFields>` element `MUST` carry a `@ref` attribute that contains a whitespace-separated list of id values that correspond to the value of the appropriate `@id` attribute for the `<ed:SupportedLexFields>` elements that are referenced.
+
In case of sub-resources, each Resource `SHOULD` support all field types that are supported by the parent resource. However, every resource `MUST` declare all supported field types independently, i.e. there is no implicit inheritance semantic.

.Example of an Endpoint Description with Lexical Search support
[#ed-lex,xml]
----
include::examples/endpoint-description-lexical-search.xml[]
----

The <<ed-lex>> shows a simple Endpoint Description for an endpoint that supports the _Lexical Search_ Capability and provides the Lex Data View, which is indicated by a `<ed:SupportedDataView>` element. It only provides one resource identified by the persistent identifier `hdl:11022/0000-0007-FE0F-C`. For this resource basic metadata such as multilingual titles, descriptions and a landing page is provided. The predominant language of the resource's content is German. 

The Generic Hits Data View and the Lex Data View are supported for this resource, because the `<ed:AvailableDataViews>` element references the `<ed:SupportedDataView>` elements via `@id` for both `hits` and `lex`. The element `<ed:AvailableLexFields>` references seven lex field types from the list of all field types the endpoints supports in `<ed:SupportedLexFields>`. Each supported field type is referenced in the space separated list of the `@ref` attribute of the `<ed:AvailableLexFields>` element pointing to the `@id` identifiers of `<ed:SupportedLexField>` elements.


== Searching and Result presentation

Queries `MUST` be formulated using the <<LexCQL,LexCQL>> query language. Results `MUST` be serialised using both the _Generic Hits_ Data View as defined in the CLARIN FCS Core Specification and the <<Lexical Data View,Lexical Data View>>. For the _Generic Hits_ Data View, the <<Extension of the Hits Data View for LexFCS,Extension of the Hits Data View for LexFCS>> `MAY` be used, which supports limited inline markup to provide extra context to Hits.
// TODO: Need explanation for why limited markup relevant: "which supports limited inline markup that allows users to X"

// Clients may decide what they support for rendering when using the LexHits Data View.

=== Request parameter x-fcs-lex-fields

This specification defines an optional request parameter `x-fcs-lex-fields` for the operation _searchRetrieve_. This parameter allows clients to specify the set of returned field types by providing a comma separated list of _Field Type Identifiers_ as described in <<lex-field-types>>. 

It overrides the server's standard behavior and `MUST` only be used in conjunction with the <<Lexical Data View,Lexical Data View>> or `MAY` be ignored silently. The parameter only modifies the result presentation, not the search process itself: requested field types that are not part of a matching entry `MUST` be ignored; no "null" or empty elements `MAY` be created.
