= Introduction
:description: Introduction of LexFCS.

The _Lexical Search for Federated Content Search (LexFCS)_ specification is an extension of the <<ref:CLARIN-FCSCore20,_CLARIN Federated Content Search (CLARIN-FCS) - Core 2.0_>> specification that allows search and retrieval of _lexical resources_ including dictionaries, encyclopedias, normative data, terminological databases, ontologies etc.


== Terminology

The key words `MUST`, `MUST NOT`, `REQUIRED`, `SHALL`, `SHALL NOT`, `SHOULD`, `SHOULD NOT`, `RECOMMENDED`, `MAY`, and `OPTIONAL` in this document are to be interpreted as in <<ref:RFC2119>>.


== Glossary

NOTE: Based on _Glossary_ in <<ref:CLARIN-FCSCore20,FCS Core 2.0>> specification.

Aggregator::
    A module or service to dispatch queries to repositories and collect results.

CLARIN-FCS, FCS::
    CLARIN federated content search, an interface specification to allow searching within resource content of repositories.

Client::
    A software component, which implements the interface specification to query Endpoints, i.e. an aggregator or a user-interface.

CQL::
    Contextual Query Language, previously known as Common Query Language, is a domain specific language for representing queries to information retrieval systems such as search engines, bibliographic catalogs and museum collection information.

Data View::
    A Data View is a mechanism to support different representations of search results, e.g. a "hits with highlights" view, an image or a geolocation.

Endpoint::
    A software component, which implements the CLARIN-FCS interface specification and translates between CLARIN-FCS and a search engine.

Hit::
    A piece of data returned by a Search Engine that matches the search criterion. What is considered a Hit highly depends on Search Engine.

Interface Specification::
    Common harmonized interface and suite of protocols that repositories need to implement.

PID::
    A Persistent identifier is a long-lasting reference to a digital object.

Repository Registry::
    A separate service that allows registering Repositories and their Endpoints and provides information about these to other components, e.g. an Aggregator. The https://centres.clarin.eu/[CLARIN Center Registry] is an implementation of such a repository registry.

Resource::
    A searchable and addressable entity at an Endpoint, such as a text corpus or a multi-modal corpus.

Resource Fragment::
    A smaller unit in a Resource, e.g. a sentence in a text corpus or a time interval in an audio transcription.

Result Set::
    An (ordered) set of hits that match a search criterion produced by a search engine as the result of processing a query.

Search Engine::
    A software component within a repository that allows for searching within the repository contents.

SRU::
    <<ref:OASIS-SRU-Overview,Search and Retrieve via URL>> is a protocol for Internet search queries. Originally introduced by Library of Congress <<ref:LOC-SRU12>>, later standardization process moved to OASIS <<ref:OASIS-SRU12>>, <<ref:OASIS-SRU20>>.


== Normative References

NOTE: Based on _Normative References_ in <<ref:CLARIN-FCSCore20,FCS Core 2.0>> specification.

[[ref:RFC2119,RFC2119]]RFC2119::
    Key words for use in RFCs to Indicate Requirement Levels, IETF RFC 2119, March 1997,
    https://www.ietf.org/rfc/rfc2119.html

[[ref:XML-Namespaces]]XML-Namespaces::
    Namespaces in XML 1.0 (Third Edition), W3C, 8 December 2009,
    http://www.w3.org/TR/2009/REC-xml-names-20091208/

[[ref:OASIS-SRU-Overview]]OASIS-SRU-Overview::
    searchRetrieve: Part 0. Overview Version 1.0, OASIS, January 2013,
    http://docs.oasis-open.org/search-ws/searchRetrieve/v1.0/os/part0-overview/searchRetrieve-v1.0-os-part0-overview.html
    http://docs.oasis-open.org/search-ws/searchRetrieve/v1.0/os/part0-overview/searchRetrieve-v1.0-os-part0-overview.doc[(DOC)],
    http://docs.oasis-open.org/search-ws/searchRetrieve/v1.0/os/part0-overview/searchRetrieve-v1.0-os-part0-overview.pdf[(PDF)]

[[ref:OASIS-SRU12]]OASIS-SRU12::
    searchRetrieve: Part 2. SRU searchRetrieve Operation: APD Binding for SRU 1.2 Version 1.0, OASIS, January 2013,
    http://docs.oasis-open.org/search-ws/searchRetrieve/v1.0/os/part2-sru1.2/searchRetrieve-v1.0-os-part2-sru1.2.html
    http://docs.oasis-open.org/search-ws/searchRetrieve/v1.0/os/part2-sru1.2/searchRetrieve-v1.0-os-part2-sru1.2.doc[(DOC)],
    http://docs.oasis-open.org/search-ws/searchRetrieve/v1.0/os/part2-sru1.2/searchRetrieve-v1.0-os-part2-sru1.2.pdf[(PDF)]

[[ref:OASIS-SRU20]]OASIS-SRU20::
    searchRetrieve: Part 3. SRU searchRetrieve Operation: APD Binding for SRU 2.0 Version 1.0, OASIS, January 2013,
    http://docs.oasis-open.org/search-ws/searchRetrieve/v1.0/os/part3-sru2.0/searchRetrieve-v1.0-os-part3-sru2.0.html
    http://docs.oasis-open.org/search-ws/searchRetrieve/v1.0/os/part3-sru2.0/searchRetrieve-v1.0-os-part3-sru2.0.doc[(DOC)],
    http://docs.oasis-open.org/search-ws/searchRetrieve/v1.0/os/part3-sru2.0/searchRetrieve-v1.0-os-part3-sru2.0.pdf[(PDF)]

[[ref:OASIS-CQL]]OASIS-CQL::
    searchRetrieve: Part 5. CQL: The Contextual Query Language version 1.0, OASIS, January 2013,
    http://docs.oasis-open.org/search-ws/searchRetrieve/v1.0/os/part5-cql/searchRetrieve-v1.0-os-part5-cql.html
    http://docs.oasis-open.org/search-ws/searchRetrieve/v1.0/os/part5-cql/searchRetrieve-v1.0-os-part5-cql.doc[(DOC)],
    http://docs.oasis-open.org/search-ws/searchRetrieve/v1.0/os/part5-cql/searchRetrieve-v1.0-os-part5-cql.pdf[(PDF)]

[[ref:LOC-SRU12]]LOC-SRU12::
    SRU Version 1.2: SRU Search/Retrieve Operation, Library of Congress,
    http://www.loc.gov/standards/sru/sru-1-2.html

[[ref:LOC-CQL]]LOC-CQL::
    The _Contextual Query Language_, Library of Congress,
    https://www.loc.gov/standards/sru/cql/,
    see also <<ref:OASIS-CQL>>

[[ref:LOC-CQLCS]]LOC-CQLCS::
    The _CQL Context Set_, Library of Congress,
    https://www.loc.gov/standards/sru/cql/contextSets/theCqlContextSet.html

//CLARIN-FCS-DataViews::
//    CLARIN Federated Content Search (CLARIN-FCS) - Data Views, SCCTC FCS Task-Force, April 2014,
//    https://trac.clarin.eu/wiki/FCS/Dataviews,
//    https://www.clarin.eu/sites/default/files/CE-2014-0317-CLARIN_FCS_Specification_DataViews_1_0.pdf

[[ref:CLARIN-FCSCore20]]CLARIN-FCSCore20::
    CLARIN Federated Content Search (CLARIN-FCS) - Core 2.0 specification, SCCTC FCS Task-Force,
    https://office.clarin.eu/v/CE-2017-1046-FCS-Specification-v89.pdf


== Non-Normative References

[[ref:UD-POS]]UD-POS::
    Universal Dependencies, Universal POS tags v2.0,
    https://universaldependencies.org/u/pos/


== Typographic and XML Namespace conventions

Sections that are still in discussion and not yet finalized are marked with `(WIP)` and may optionally have some _NOTE_ admonition blocks. Details and specifications `MUST NOT` be considered stable.

The following typographic conventions for XML fragments will be used throughout this specification:

* `<prefix:Element>`
+
An XML element with the Generic Identifier _Element_ that is bound to an XML namespace denoted by the prefix _prefix_.

* `@attr`
+
An XML attribute with the name _attr_.

* `string`
+
The literal _string_ must be used either as element content or attribute value.

Endpoints and Clients `MUST` adhere to the <<ref:XML-Namespaces>> specification. The CLARIN-FCS interface specification generally does not dictate whether XML elements should be serialized in their prefixed or non-prefixed syntax, but Endpoints `MUST` ensure that the correct XML namespace is used for elements and that XML namespaces are declared correctly. Clients `MUST` be agnostic regarding syntax for serializing the XML elements, i.e. if the prefixed or un-prefixed variant was used, and `SHOULD` operate solely on _expanded names_, i.e. pairs of _namespace name_ and _local name_.

For a list of common XML namespace names and prefixes see the table "XML Namespaces and prefixes" in section 1.5 of the <<ref:CLARIN-FCSCore20,FCS Core 2.0 Specification>>.
