name: build <fcs-endpoint-dev-slides> adocs slides

on:
  push:
    branches:
      - main
      - dev
      - fcs-endpoint-dev-slides
    paths:
      - 'fcs-endpoint-dev-slides/**'
      - '.github/workflows/build-fcs-endpoint-dev-slides-adoc.yml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    container: asciidoctor/docker-asciidoctor

    steps:
      - uses: actions/checkout@v3

      - name: Setup reveal.js
        run: |
          git clone -b 4.1.2 --depth 1 https://github.com/hakimel/reveal.js.git
          mkdir -p slides/reveal.js
          mv reveal.js/dist slides/reveal.js/
          mv reveal.js/plugin slides/reveal.js/

      - name: Setup highlight.js for reveal.js
        run: |
          git clone -b 10.7.3 --depth 1 https://github.com/highlightjs/highlight.js.git
          cp highlight.js/src/styles/github.css slides/reveal.js/plugin/highlight/
          cp highlight.js/src/styles/idea.css slides/reveal.js/plugin/highlight/
          cp highlight.js/src/styles/magula.css slides/reveal.js/plugin/highlight/

      - name: Build slides
        run: asciidoctor-revealjs -v -D slides index.adoc
  
      - name: Copy slide resources
        run: |
          mv -v images slides/
          mv -v css slides/

      - name: Store results
        uses: actions/upload-artifact@v3
        with:
          name: fcs-endpoint-dev-slides
          path: slides/*
