name: build <fcs-dataviews-1.0> adocs

on:
  push:
    branches:
      - main
      - dev
    paths:
      - 'fcs-dataviews-1.0/**'
      - '.github/workflows/build-fcs-dataviews-adoc.yml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    container: asciidoctor/docker-asciidoctor

    steps:
      - uses: actions/checkout@v4

      - name: Build HTML
        run: asciidoctor -v -D docs -a data-uri --backend=html5 -o fcs-dataviews-1.0.html fcs-dataviews-1.0/index.adoc

      - name: Build PDF
        run: asciidoctor-pdf -v -D docs -o fcs-dataviews-1.0.pdf fcs-dataviews-1.0/index.adoc

      - name: Store results
        uses: actions/upload-artifact@v4
        with:
          name: fcs-dataviews-1.0-specs
          path: docs/*
