name: build <lexfcs-1> adocs 

on:
  push:
    branches:
      - main
    paths:
      - 'lexfcs-1/**'
      - '.github/workflows/build-lexfcs-1-adoc.yml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    container: asciidoctor/docker-asciidoctor

    steps:
      - name: Install fonts
        run: |
          mkdir -p /usr/share/fonts/truetype/vlgothic
          curl -L -o /usr/share/fonts/truetype/vlgothic/VL-PGothic-Regular.ttf https://github.com/deepin-community/fonts-vlgothic/raw/refs/heads/master/VL-PGothic-Regular.ttf

      - uses: actions/checkout@v7

      - name: Build HTML
        run: asciidoctor -v -D docs -a data-uri --backend=html5 -o lexfcs-1.html lexfcs-1/index.adoc

      - name: Build PDF
        run: asciidoctor-pdf -v -r ./lexfcs-1/scripts/pdf-converter-custom-title-page-with-acknowledgment.rb --trace -D docs -o lexfcs-1.pdf lexfcs-1/index.adoc

      - name: Copy attachments
        run: cp -R lexfcs-1/attachments docs/

      - name: Store results
        uses: actions/upload-artifact@v7
        with:
          name: lexfcs-1-specs
          path: docs/*
